In [2]:
import numpy as np
arr=np.array([1, 2, 3, 4])
print(arr.ndim)

1


In [13]:
g = np.array([['a', 'b'],['c', 'd']])
g.dtype.name

'str32'

In [2]:
import numpy as np
f = np.array([[1, 2, 3],[4, 5, 6]], dtype='complex')
print(f)
print(f.dtype)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]
complex128


In [6]:
import numpy as np
data = np.genfromtxt('sample.csv', delimiter=',', dtype=('i4','i2','a12','a1'))
data

array([(       -1, -1, b'Student Name', b'S'),
       (210962052,  1, b'SIDDHANT KUM', b'B'),
       (210962055,  2, b'NANDHANA SAN', b'B'),
       (210962108,  3, b'SEVVA NITHIN', b'B'),
       (210962176,  4, b'SAI HARSHINI', b'B'),
       (220962001,  5, b'BHARATH KUMA', b'B'),
       (220962003,  6, b'SUCHIT GUPTA', b'B'),
       (220962004,  7, b'VARUN PRABHU', b'B'),
       (220962012,  8, b'YASHAS S', b'B'),
       (220962013,  9, b'NIKHIL NAIR', b'B'),
       (220962021, 10, b'ARNAV SANJAY', b'B'),
       (220962026, 11, b'AKULA OMKAR', b'B'),
       (220962032, 12, b'ARHAM DUGAR', b'B')],
      dtype=[('f0', '<i4'), ('f1', '<i2'), ('f2', 'S12'), ('f3', 'S1')])

In [21]:
data['Roll_No']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int16)

In [23]:
data['Student_Name']

array([b'SIDDHANT KUMAR', b'NANDHANA SANTHO', b'SEVVA NITHIN SR',
       b'SAI HARSHINI U', b'BHARATH KUMAR', b'SUCHIT GUPTA',
       b'VARUN PRABHU SH', b'YASHAS S', b'NIKHIL NAIR',
       b'ARNAV SANJAY KA', b'AKULA OMKAR', b'ARHAM DUGAR'], dtype='|S15')

In [24]:
data[1]

(210962055, 2, b'NANDHANA SANTHO', b'B')

In [36]:
import pandas as pd

In [2]:
import numpy as np
A=np.arange(16).reshape(4,4)
A



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
import numpy as np
[A1,A2,A3] = np.split(A,[0,3],axis=0)
A1,A2,A3
##For example, [2, 3] would, for axis=0, result in
#ary[:2]
#ary[2:3]
#ary[3:]

(array([], shape=(0, 4), dtype=int32),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]))

In [4]:
import pandas as pd
s1=pd.Series([ 1,2,6,10,12])
s1

0     1
1     2
2     6
3    10
4    12
dtype: int64

In [5]:
s2=pd.Series([ 1,2,6,10,12], index=['a','b','c','d','e'])
s2

a     1
b     2
c     6
d    10
e    12
dtype: int64

In [30]:
s2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [31]:
s2.values

array([ 1,  2,  6, 10, 12], dtype=int64)

In [32]:
s2['b']

2

In [7]:
s2['a':'c']

a    1
b    2
c    6
dtype: int64

In [34]:
s2[3]

10

In [8]:
serd = pd.Series([1,0,2,1,2,3], index=['white','white','blue','green','green','yellow'])
serd

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [10]:
serd.unique()
serd['white':'green']

white    1
white    0
blue     2
green    1
green    2
dtype: int64

In [40]:
serd.value_counts()

1    2
2    2
0    1
3    1
dtype: int64

In [41]:
serd.isin([2,1])

white      True
white     False
blue       True
green      True
green      True
yellow    False
dtype: bool

In [42]:
serd[serd.isin([2,1])]

white    1
blue     2
green    1
green    2
dtype: int64

In [3]:
import pandas as pd
import numpy as np
s3=pd.Series([1,5,'ab',np.NaN,np.nan,25])
s3

0      1
1      5
2     ab
3    NaN
4    NaN
5     25
dtype: object

In [4]:
s3.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [5]:
s3.notnull()

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [12]:
mydict1={'red':400,'blue':300,'green':600,'white':900}
myseries1=pd.Series(mydict1)
mydict2={'red':300,'brown':100,'green':600,'black':400}
myseries2=pd.Series(mydict2)
myseries2


red      300
brown    100
green    600
black    400
dtype: int64

In [17]:
import pandas as pd
mydict = {'red': 2000, 'blue': 1000, 'yellow': 500, 'orange': 1000}
myseries= pd.Series(mydict)
myseries

red       2000
blue      1000
yellow     500
orange    1000
dtype: int64

In [50]:
myseries1+myseries2

black       NaN
blue        NaN
brown       NaN
green    1200.0
red       500.0
white       NaN
dtype: float64

In [13]:
import pandas as pd
data = {'color' : ['blue','green','yellow','red','white'],
'object' : ['ball','pen','pencil','paper','mug'],
'price' : [1.2,1.0,0.6,0.9,1.7]}
frame = pd.DataFrame(data)
frame

color  object  price
0    blue    ball    1.2
1   green     pen    1.0
2  yellow  pencil    0.6
3     red   paper    0.9
4   white     mug    1.7

In [15]:
frame2 = pd.DataFrame(data, index=['one','two','three','four','five'])
frame2

color  object  price
one      blue    ball    1.2
two     green     pen    1.0
three  yellow  pencil    0.6
four      red   paper    0.9
five    white     mug    1.7

In [16]:
frame2.columns
frame2.values
frame2[1:3]
frame2['object'][3]
print(frame2.loc['two'])


color  object  price
two     green     pen    1.0
three  yellow  pencil    0.6

In [17]:
frame2['new'] = 12
frame2['new'] = [3.0,1.3,2.2,0.8,1.1]
frame2


color  object  price  new
one      blue    ball    1.2  3.0
two     green     pen    1.0  1.3
three  yellow  pencil    0.6  2.2
four      red   paper    0.9  0.8
five    white     mug    1.7  1.1

In [2]:
import pandas as pd 

nestdict = {'red':{2012: 22, 2013: 33},
'white':{2011: 13, 2012: 22, 2013: 16},
'blue': {2011: 17, 2012: 27, 2013: 18}}

frame4 = pd.DataFrame(nestdict)
frame4



red  white  blue
2012  22.0     22    27
2013  33.0     16    18
2011   NaN     13    17

In [11]:
ser = pd.Series([5,0,3,8,4], index=['red','blue','yellow','white','green'])
ser
ser.index
ser.index=['black','blue','yellow','white','green']
ser

ValueError: Length mismatch: Expected axis has 5 elements, new values have 6 elements

In [8]:


ser.idxmax()
ser.index.is_unique
ser.idxmin()
ser.idxmax()

'white'

In [10]:
ser = pd.Series([2,5,7,4], index=['one','two','three','four'])
ser
ser1=ser.reindex(['three','four','five','one','two'])
ser1


three    7.0
four     4.0
five     NaN
one      2.0
two      5.0
dtype: float64

In [13]:
ser3=pd.Series([5,6,3],index=[3,5,6])
ser3


3    5
5    6
6    3
dtype: int64

In [14]:
ser3.reindex(range(6),method='ffill')


0    NaN
1    NaN
2    NaN
3    5.0
4    5.0
5    6.0
dtype: float64

In [15]:
ser3.reindex(range(7),method='bfill')


0    5
1    5
2    5
3    5
4    6
5    6
6    3
dtype: int64

In [22]:
import numpy as np
s1 = pd.Series([3,2,5,1],['white','yellow','green','blue'])
s1.drop('yellow')
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil','paper'])
frame
frame.drop(['pen','pencil'],axis=1)


ball  paper
red        0      3
blue       4      7
yellow     8     11
white     12     15

In [40]:
s2 = pd.Series([1,4,7,2,1],['white','yellow','black','blue','brown'])
s2

white     1
yellow    4
black     7
blue      2
brown     1
dtype: int64

In [41]:
s1+s2

black     NaN
blue      3.0
brown     NaN
green     NaN
white     4.0
yellow    6.0
dtype: float64

In [27]:
frame1 = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil','paper'])
frame1
frame2 = pd.DataFrame(np.arange(12).reshape((4,3)),
index=['blue','green','white','yellow'],
columns=['mug','pen','ball'])
frame2
frame1+frame2

ball  mug  paper   pen  pencil
blue     6.0  NaN    NaN   6.0     NaN
green    NaN  NaN    NaN   NaN     NaN
red      NaN  NaN    NaN   NaN     NaN
white   20.0  NaN    NaN  20.0     NaN
yellow  19.0  NaN    NaN  19.0     NaN

In [10]:
import numpy as np
frame = pd.DataFrame(np.arange(16).reshape((4,4)),
index=['red','blue','yellow','white'],
columns=['ball','pen','pencil','paper'])
frame
ser = pd.Series(np.arange(4),  index=['ball','pen','pencil','paper'])
ser

ball      0
pen       1
pencil    2
paper     3
dtype: int32

In [31]:
frame

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [34]:
frame
f = lambda x: x.max() - x.min()
frame.apply(f)


ball      12
pen       12
pencil    12
paper     12
dtype: int64

In [12]:
ser = pd.Series(np.arange(4),  index=['ball','pen','pencil','paper'])
ser

ball      0
pen       1
pencil    2
paper     3
dtype: int32

In [14]:
ser.rank()

ball      1.0
pen       2.0
pencil    3.0
paper     4.0
dtype: float64

In [52]:
frame1


ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [53]:
frame1.sum()

ball      24
pen       28
pencil    32
paper     36
dtype: int64

In [56]:
frame1.sort_index()

ball  pen  pencil  paper
blue       4    5       6      7
red        0    1       2      3
white     12   13      14     15
yellow     8    9      10     11

In [50]:
frame1.sort_index()

ball  pen  pencil  paper
blue       4    5       6      7
red        0    1       2      3
white     12   13      14     15
yellow     8    9      10     11

In [52]:
frame1.describe()

ball        pen     pencil      paper
count   4.000000   4.000000   4.000000   4.000000
mean    6.000000   7.000000   8.000000   9.000000
std     5.163978   5.163978   5.163978   5.163978
min     0.000000   1.000000   2.000000   3.000000
25%     3.000000   4.000000   5.000000   6.000000
50%     6.000000   7.000000   8.000000   9.000000
75%     9.000000  10.000000  11.000000  12.000000
max    12.000000  13.000000  14.000000  15.000000

In [5]:
import pandas as pd
seq = pd.Series([1,2,3,4,4,3,2,1],['2006','2007','2008','2009','2010','2011','2012','2013'])
seq

2006    1
2007    2
2008    3
2009    4
2010    4
2011    3
2012    2
2013    1
dtype: int64

In [7]:
seq2 = pd.Series([3,4,3,4,5,4,3,2],['2006','2007','2008','2009','2010','2011','2012','2013'])
seq2

2006    3
2007    4
2008    3
2009    4
2010    5
2011    4
2012    3
2013    2
dtype: int64

In [8]:
seq.corr(seq2)

0.7745966692414835

In [9]:
seq.cov(seq2)

0.8571428571428571

In [15]:
import numpy as np
ser = pd.Series([0,1,2,np.NaN,9], index=['red','blue','yellow','white','green'])
ser

red       0.0
blue      1.0
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [16]:
ser.dropna()

red       0.0
blue      1.0
yellow    2.0
green     9.0
dtype: float64

In [17]:
ser

red       0.0
blue      1.0
yellow    2.0
white     NaN
green     9.0
dtype: float64

In [18]:
ser[ser.notnull()]

red       0.0
blue      1.0
yellow    2.0
green     9.0
dtype: float64

In [21]:
frame1

ball  pen  pencil  paper
red        0    1       2      3
blue       4    5       6      7
yellow     8    9      10     11
white     12   13      14     15

In [35]:
frame3 = pd.DataFrame([[6,np.nan,6],[np.nan,np.nan,np.nan],[2,np.nan,5]],index = ['blue','green','red'],
columns = ['ball','mug','pen'])
frame3

ball  mug  pen
blue    6.0  NaN  6.0
green   NaN  NaN  NaN
red     2.0  NaN  5.0

In [36]:
frame3.dropna()

Empty DataFrame
Columns: [ball, mug, pen]
Index: []

In [37]:
frame3.dropna(how='all')

ball  mug  pen
blue   6.0  NaN  6.0
red    2.0  NaN  5.0

In [15]:
 mser = pd.Series(np.random.rand(8), index=[['white','white','white','blue','blue','red','red','red'], 
                                            ['up','down','right','up','down','up','down','left']])
mser


white  up       0.669757
       down     0.793695
       right    0.146867
blue   up       0.375137
       down     0.919820
red    up       0.842327
       down     0.709571
       left     0.214655
dtype: float64

In [64]:
mser.index

MultiIndex([('white',    'up'),
            ('white',  'down'),
            ('white', 'right'),
            ( 'blue',    'up'),
            ( 'blue',  'down'),
            (  'red',    'up'),
            (  'red',  'down'),
            (  'red',  'left')],
           )

In [16]:
mser['white','up']
mser[:,'up']

white    0.669757
blue     0.375137
red      0.842327
dtype: float64

In [67]:
mser.unstack()
mser

white  up       0.201333
       down     0.982497
       right    0.327243
blue   up       0.935599
       down     0.441811
red    up       0.270120
       down     0.595335
       left     0.060631
dtype: float64

In [17]:
mframe = pd.DataFrame(np.random.randn(16).reshape(4,4),
index=[['white','white','red','red'], ['up','down','up','down']],
columns=[['pen','pen','paper','paper'],[1,2,1,2]])
mframe


pen               paper          
                   1         2         1         2
white up    0.131503 -1.140751 -0.364618  1.285599
      down -1.406557 -0.039601  0.529281  0.195595
red   up   -0.650075  1.375255 -0.049094  0.083346
      down  0.486796  0.402862  2.034860 -0.074889

In [20]:
mframe.columns.names = ['objects','id']
mframe.index.names = ['colors','status']
mframe

objects             pen               paper          
id                    1         2         1         2
colors status                                        
white  up      0.131503 -1.140751 -0.364618  1.285599
       down   -1.406557 -0.039601  0.529281  0.195595
red    up     -0.650075  1.375255 -0.049094  0.083346
       down    0.486796  0.402862  2.034860 -0.074889

In [22]:
mframe.sum(level='colors')

C:\Users\MAHE\AppData\Local\Temp\ipykernel_14068\3153633550.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  mframe.sum(level='colors')


objects       pen               paper          
id              1         2         1         2
colors                                         
white   -1.275054 -1.180352  0.164663  1.481194
red     -0.163279  1.778117  1.985765  0.008457

In [24]:
mframe.sum(level='id',axis=1)


C:\Users\MAHE\AppData\Local\Temp\ipykernel_14068\532524265.py:1: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().
  mframe.sum(level='id',axis=1)


id                    1         2
colors status                    
white  up     -0.233115  0.144848
       down   -0.877276  0.155994
red    up     -0.699169  1.458601
       down    2.521656  0.327973

In [32]:
a = [np.random.randint(0,20) for i in range(10)]
a

[0, 1, 19, 12, 16, 7, 1, 11, 12, 12]

In [33]:
type(a)

list

In [35]:
#np.unique(a)
np.array(set(a))

array({0, 1, 7, 11, 12, 16, 19}, dtype=object)