In [1]:
import pandas as pd
import numpy as np

In [2]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
'price': [12.33,11.44,33.21,13.23,33.62]})
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [3]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
'color': ['white','red','red','black']})
frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

In [4]:
pd.merge(frame1,frame2)

id  price  color
0    ball  12.33    red
1  pencil  11.44  white
2  pencil  11.44    red
3     pen  33.21  black

In [5]:
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
'color': ['white','red','red','black','green'],
'brand': ['OMG','ABC','ABC','POD','POD']})
frame1

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [6]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
'brand': ['OMG','POD','ABC','POD']})
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [7]:
pd.merge(frame1,frame2)

Empty DataFrame
Columns: [id, color, brand]
Index: []

In [8]:
pd.merge(frame1,frame2,on='id')

id  color brand_x brand_y
0    ball  white     OMG     ABC
1  pencil    red     ABC     OMG
2  pencil    red     ABC     POD
3     pen    red     ABC     POD

In [9]:
frame2.columns = ['brand','sid']
frame2

brand  sid
0  pencil  OMG
1  pencil  POD
2    ball  ABC
3     pen  POD

In [10]:
pd.merge(frame1, frame2)

Empty DataFrame
Columns: [id, color, brand, sid]
Index: []

In [11]:
pd.merge(frame1,frame2,how='outer')

id  color   brand  sid
0     ball  white     OMG  NaN
1   pencil    red     ABC  NaN
2      pen    red     ABC  NaN
3      mug  black     POD  NaN
4  ashtray  green     POD  NaN
5      NaN    NaN  pencil  OMG
6      NaN    NaN  pencil  POD
7      NaN    NaN    ball  ABC
8      NaN    NaN     pen  POD

In [12]:
pd.merge(frame1,frame2,right_index=True, left_index=True)

id  color brand_x brand_y  sid
0    ball  white     OMG  pencil  OMG
1  pencil    red     ABC  pencil  POD
2     pen    red     ABC    ball  ABC
3     mug  black     POD     pen  POD

In [13]:
frame2.columns = ['brand2','id2']
frame1.join(frame2)

id  color brand  brand2  id2
0     ball  white   OMG  pencil  OMG
1   pencil    red   ABC  pencil  POD
2      pen    red   ABC    ball  ABC
3      mug  black   POD     pen  POD
4  ashtray  green   POD     NaN  NaN

In [14]:
array = np.arange(9).reshape((3,3))
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
array2 = np.arange(9).reshape((3,3))+6
array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [16]:
np.concatenate([array,array2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [17]:
np.concatenate([array,array2],axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [18]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser1

1    0.616843
2    0.644174
3    0.383157
4    0.699973
dtype: float64

In [19]:
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])
ser2

5    0.538133
6    0.747102
7    0.071256
8    0.715713
dtype: float64

In [20]:
pd.concat([ser1,ser2], axis=0)

1    0.616843
2    0.644174
3    0.383157
4    0.699973
5    0.538133
6    0.747102
7    0.071256
8    0.715713
dtype: float64

In [21]:
pd.concat([ser1,ser2],axis=1)

0         1
1  0.616843       NaN
2  0.644174       NaN
3  0.383157       NaN
4  0.699973       NaN
5       NaN  0.538133
6       NaN  0.747102
7       NaN  0.071256
8       NaN  0.715713

In [22]:
pd.concat([ser1,ser2], keys=[1,2])

1  1    0.616843
   2    0.644174
   3    0.383157
   4    0.699973
2  5    0.538133
   6    0.747102
   7    0.071256
   8    0.715713
dtype: float64

In [23]:
pd.concat([ser1,ser2], axis=1, keys=[1,2])

1         2
1  0.616843       NaN
2  0.644174       NaN
3  0.383157       NaN
4  0.699973       NaN
5       NaN  0.538133
6       NaN  0.747102
7       NaN  0.071256
8       NaN  0.715713

In [24]:
ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])
ser1

1    0.250474
2    0.760394
3    0.561518
4    0.900063
5    0.406006
dtype: float64

In [25]:
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])
ser2

2    0.239208
4    0.636677
5    0.677419
6    0.627516
dtype: float64

In [26]:
ser1.combine_first(ser2)

1    0.250474
2    0.760394
3    0.561518
4    0.900063
5    0.406006
6    0.627516
dtype: float64

In [27]:
ser2.combine_first(ser1)

1    0.250474
2    0.239208
3    0.561518
4    0.636677
5    0.677419
6    0.627516
dtype: float64

In [28]:
ser1.combine_first(ser2)

1    0.250474
2    0.760394
3    0.561518
4    0.900063
5    0.406006
6    0.627516
dtype: float64

In [29]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
index=['white','black','red'],
columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [30]:
frame1.stack()

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int64

In [31]:
frame1.unstack()

ball    white    0
        black    3
        red      6
pen     white    1
        black    4
        red      7
pencil  white    2
        black    5
        red      8
dtype: int64

In [32]:
longframe = pd.DataFrame({ 'color':['white','white','white',
'red','red','red',
'black','black','black'],
'item':['ball','pen','mug',
'ball','pen','mug',
'ball','pen','mug'],
 'value': np.random.rand(9)})
longframe

color  item     value
0  white  ball  0.268978
1  white   pen  0.026884
2  white   mug  0.271542
3    red  ball  0.461598
4    red   pen  0.187413
5    red   mug  0.671052
6  black  ball  0.711209
7  black   pen  0.365914
8  black   mug  0.527417

In [33]:
wideframe = longframe.pivot(columns=['color','item'])
wideframe

value                                                              \
color     white                           red                         black   
item       ball       pen       mug      ball       pen       mug      ball   
0      0.268978       NaN       NaN       NaN       NaN       NaN       NaN   
1           NaN  0.026884       NaN       NaN       NaN       NaN       NaN   
2           NaN       NaN  0.271542       NaN       NaN       NaN       NaN   
3           NaN       NaN       NaN  0.461598       NaN       NaN       NaN   
4           NaN       NaN       NaN       NaN  0.187413       NaN       NaN   
5           NaN       NaN       NaN       NaN       NaN  0.671052       NaN   
6           NaN       NaN       NaN       NaN       NaN       NaN  0.711209   
7           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
8           NaN       NaN       NaN       NaN       NaN       NaN       NaN   

                           
color                      
item        pen       mug  
0           NaN       NaN  
1           NaN       NaN  
2           NaN       NaN  
3           NaN       NaN  
4           NaN       NaN  
5           NaN       NaN  
6           NaN       NaN  
7      0.365914       NaN  
8           NaN  0.527417

In [34]:
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [35]:
del frame1['ball'] #Delete Column
frame3=frame1.drop(['white','black']) #Delete Row
frame3

pen  pencil
red    7       8

In [36]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
'value': [2,1,3,3,2]})
dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [37]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [38]:
dframe[dframe.duplicated()]


color  value
3    red      3
4  white      2

In [39]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
'color':['white','rosso','verde','black','yellow'],
'price':[5.56,4.20,1.30,0.56,2.75]})
frame

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [40]:
newcolors = {'pencil': 'red1','black': 'green1' }
newcolors

{'pencil': 'red1', 'black': 'green1'}

In [41]:
frame.replace(newcolors)#Parameter is a Dictionary and values are replaced accordingly

item   color  price
0     ball   white   5.56
1      mug   rosso   4.20
2      pen   verde   1.30
3     red1  green1   0.56
4  ashtray  yellow   2.75

In [42]:
ser = pd.Series([1,3,np.nan,4,6,np.nan,3])
ser

0    1.0
1    3.0
2    NaN
3    4.0
4    6.0
5    NaN
6    3.0
dtype: float64

In [43]:
ser.replace(np.nan,0)

0    1.0
1    3.0
2    0.0
3    4.0
4    6.0
5    0.0
6    3.0
dtype: float64

In [44]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
'color':['white','red','green','black','yellow']})
frame

item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [45]:
price = {'ball' : 5.56,'mug' : 4.20,'bottle' : 1.30,'scissors' : 3.41,'pen' : 1.30,'pencil' : 0.56,'ashtray' : 2.75 }
price

{'ball': 5.56,
 'mug': 4.2,
 'bottle': 1.3,
 'scissors': 3.41,
 'pen': 1.3,
 'pencil': 0.56,
 'ashtray': 2.75}

In [46]:
frame['price'] = frame['item'].map(price)
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [47]:
reindex = {
0: 'first',1: 'second',2: 'third',3: 'fourth',4: 'fifth'}

In [48]:
frame.rename(reindex)

item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [49]:
recolumn = {'item':'object','price': 'value'}
frame.rename(index=reindex, columns=recolumn)

object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

In [50]:
frame.rename(index={1:'first'}, columns={'item':'object'})

object   color  price
0         ball   white   5.56
first      mug     red   4.20
2          pen   green   1.30
3       pencil   black   0.56
4      ashtray  yellow   2.75

In [51]:
frame.rename(columns={'object':'object1'}, inplace=True)
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [52]:
results = [12,34,67,55,28,90,99,12,3,56,74,44,87,23,49,89,87]
results

[12, 34, 67, 55, 28, 90, 99, 12, 3, 56, 74, 44, 87, 23, 49, 89, 87]

In [53]:
bins = [0,25,50,75,100]
bins

[0, 25, 50, 75, 100]

In [54]:
cat = pd.cut(results, bins)
cat

[(0, 25], (25, 50], (50, 75], (50, 75], (25, 50], ..., (75, 100], (0, 25], (25, 50], (75, 100], (75, 100]]
Length: 17
Categories (4, interval[int64, right]): [(0, 25] < (25, 50] < (50, 75] < (75, 100]]

In [55]:
cat.dtype

CategoricalDtype(categories=[(0, 25], (25, 50], (50, 75], (75, 100]], ordered=True, categories_dtype=interval[int64, right])

In [56]:
pd.value_counts(cat)

/tmp/ipykernel_3317/764800318.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cat)


(75, 100]    5
(0, 25]      4
(25, 50]     4
(50, 75]     4
Name: count, dtype: int64

In [57]:
bin_names = ['unlikely','less likely','likely','highly likely']
cat1= pd.cut(results, bins, labels=bin_names)

In [58]:
df = pd.DataFrame(cat1.value_counts())
df

count
unlikely           4
less likely        4
likely             4
highly likely      5

In [59]:
cuts=pd.cut(results, 3)
cuts
pd.value_counts(cuts)

/tmp/ipykernel_3317/2973330025.py:3: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(cuts)


(2.904, 35.0]    6
(67.0, 99.0]     6
(35.0, 67.0]     5
Name: count, dtype: int64

In [60]:
quintiles = pd.qcut(results, 5)
quintiles

[(2.999, 24.0], (24.0, 46.0], (62.6, 87.0], (46.0, 62.6], (24.0, 46.0], ..., (62.6, 87.0], (2.999, 24.0], (46.0, 62.6], (87.0, 99.0], (62.6, 87.0]]
Length: 17
Categories (5, interval[float64, right]): [(2.999, 24.0] < (24.0, 46.0] < (46.0, 62.6] < (62.6, 87.0] < (87.0, 99.0]]

In [61]:
pd.value_counts(quintiles)

/tmp/ipykernel_3317/194218986.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quintiles)


(2.999, 24.0]    4
(62.6, 87.0]     4
(24.0, 46.0]     3
(46.0, 62.6]     3
(87.0, 99.0]     3
Name: count, dtype: int64

In [62]:
randframe = pd.DataFrame(np.random.randn(100,3))
randframe

0         1         2
0   1.287638  0.453934 -0.544074
1  -0.187727  0.378652  0.799911
2   0.788011 -1.342058  0.794330
3   1.345732 -1.749168  0.201166
4   0.617793  1.340719 -1.296624
..       ...       ...       ...
95  0.137105 -0.390687  0.243597
96 -0.127591 -0.784771  2.121955
97  1.140073  1.514941 -1.236642
98 -0.914024  1.358078 -1.082806
99  0.566451  1.765842 -0.217033

[100 rows x 3 columns]

In [63]:
randframe.describe()

0           1           2
count  100.000000  100.000000  100.000000
mean     0.289575    0.021784   -0.137480
std      0.994950    1.100546    0.927572
min     -2.041997   -2.887453   -2.225048
25%     -0.358473   -0.680639   -0.773251
50%      0.166442    0.034118   -0.164576
75%      0.898947    0.795974    0.491870
max      2.591427    2.772198    2.657827

In [64]:
randframe.std()

0    0.994950
1    1.100546
2    0.927572
dtype: float64

In [128]:
randframe[(np.abs(randframe) > (2*randframe.std())).any(1)] # Problem 

TypeError: DataFrame.any() takes 1 positional argument but 2 were given

In [65]:
nframe = pd.DataFrame(np.arange(25).reshape(5,5))
nframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [66]:
new_order = np.random.permutation(5)
new_order

array([0, 3, 1, 4, 2])

In [67]:
nframe.take(new_order)

0   1   2   3   4
0   0   1   2   3   4
3  15  16  17  18  19
1   5   6   7   8   9
4  20  21  22  23  24
2  10  11  12  13  14

In [68]:
new_order = [3,4,2]
np.random.permutation(new_order)

array([3, 2, 4])

In [69]:
nframe.take(new_order)

0   1   2   3   4
3  15  16  17  18  19
4  20  21  22  23  24
2  10  11  12  13  14

In [70]:
gg = pd.DataFrame(np.arange(0,6).reshape(2,3))
gg

0  1  2
0  0  1  2
1  3  4  5

In [71]:
len(gg)#Number of Rows

2

In [72]:
sample = np.arange(len(nframe))
np.random.shuffle(sample)
sample

array([0, 2, 3, 1, 4])

In [73]:
nframe.take(sample)

0   1   2   3   4
0   0   1   2   3   4
2  10  11  12  13  14
3  15  16  17  18  19
1   5   6   7   8   9
4  20  21  22  23  24

In [74]:
text = '16 Bolton Avenue , Boston'


In [75]:
text.split(',')


['16 Bolton Avenue ', ' Boston']

In [76]:
address, city = [s.strip() for s in text.split(',')]    
address

'16 Bolton Avenue'

In [77]:
city

'Boston'

In [78]:
text.index('Boston')


19

In [79]:
text.find('Boston')

19

In [80]:
address + ',' + city


'16 Bolton Avenue,Boston'

In [81]:
text.count('e')                     

2

In [82]:
text.replace('Avenue','Street')


'16 Bolton Street , Boston'

In [83]:
text = "This is an\t odd \n text!"
print(text)

This is an	 odd 
 text!


In [84]:
import re
re.split('\s+', text)

['This', 'is', 'an', 'odd', 'text!']

In [85]:
regex = re.compile('\s+')    
s=regex.split(text)
s

['This', 'is', 'an', 'odd', 'text!']

In [86]:
type(s)

list

In [87]:
text1 = 'This is my address: FC6,CSE Dept, AB5, MIT, Manipal'
text1

'This is my address: FC6,CSE Dept, AB5, MIT, Manipal'

In [88]:
re.findall('a\w+',text1)

['address', 'anipal']

In [89]:
re.search('[A,a]\w+',text)

<re.Match object; span=(8, 10), match='an'>

In [90]:
search = re.search('[A,a]\w+',text)

In [91]:
search.start()

8

In [92]:
re.match('T\w+',text)

<re.Match object; span=(0, 4), match='This'>

In [93]:
frame = pd.DataFrame({ 'color': ['white','red','green','red','green'],
'object': ['pen','pencil','pencil','ashtray','pen'],
'price1' : [5.56,4.20,1.30,0.56,2.75],
'price2' : [4.75,4.12,1.60,0.75,3.15]})
frame


color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [94]:
group = frame['price1'].groupby(frame['color'])
group


In [95]:
group.groups


{'green': [2, 4], 'red': [1, 3], 'white': [0]}

In [96]:
group.mean()

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [97]:
group.sum()

color
green    4.05
red      4.76
white    5.56
Name: price1, dtype: float64

In [98]:
ggroup = frame['price1'].groupby([frame['color'],frame['object']])
ggroup.groups

{('green', 'pen'): [4], ('green', 'pencil'): [2], ('red', 'ashtray'): [3], ('red', 'pencil'): [1], ('white', 'pen'): [0]}

In [99]:
ggroup.sum()

color  object 
green  pen        2.75
       pencil     1.30
red    ashtray    0.56
       pencil     4.20
white  pen        5.56
Name: price1, dtype: float64

In [100]:
#frame.groupby(frame['color'].mean())

In [101]:
frame

color   object  price1  price2
0  white      pen    5.56    4.75
1    red   pencil    4.20    4.12
2  green   pencil    1.30    1.60
3    red  ashtray    0.56    0.75
4  green      pen    2.75    3.15

In [102]:
for name, group in frame.groupby('color'):
    print(name)
    print(group)

green
   color  object  price1  price2
2  green  pencil    1.30    1.60
4  green     pen    2.75    3.15
red
  color   object  price1  price2
1   red   pencil    4.20    4.12
3   red  ashtray    0.56    0.75
white
   color object  price1  price2
0  white    pen    5.56    4.75


In [103]:
result1 = frame['price1'].groupby(frame['color']).mean()
result1

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [104]:
result2 = frame.groupby(frame['color']).mean()
result2

TypeError: agg function failed [how->mean,dtype->object]

In [105]:
type(result1)

pandas.core.series.Series

In [106]:
type(result2)

NameError: name 'result2' is not defined

In [107]:
(frame.groupby(frame['color']).mean())['price1']

TypeError: agg function failed [how->mean,dtype->object]

In [108]:
means = frame.groupby('color').mean().add_prefix('mean_')
means

TypeError: agg function failed [how->mean,dtype->object]

In [109]:
group = frame.groupby('color')
group

In [110]:
group['price1'].quantile(0.6)

color
green    2.170
red      2.744
white    5.560
Name: price1, dtype: float64

In [111]:
group['price1'].agg('std')

color
green    1.025305
red      2.573869
white         NaN
Name: price1, dtype: float64

In [112]:
group['price1'].agg('mean')

color
green    2.025
red      2.380
white    5.560
Name: price1, dtype: float64

In [113]:
frame = pd.DataFrame({ 'color':['white','red','green','red','green'],
'price1':[5.56,4.20,1.30,0.56,2.75],
'price2':[4.75,4.12,1.60,0.75,3.15]})
frame

color  price1  price2
0  white    5.56    4.75
1    red    4.20    4.12
2  green    1.30    1.60
3    red    0.56    0.75
4  green    2.75    3.15

In [114]:
sums = frame.groupby('color').sum().add_prefix('tot_')
sums

tot_price1  tot_price2
color                        
green        4.05        4.75
red          4.76        4.87
white        5.56        4.75

In [115]:
frame.groupby('color').transform(np.sum).add_prefix('tot_')

/tmp/ipykernel_3317/147351506.py:1: FutureWarning: The provided callable <function sum at 0x7f46ec7367a0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  frame.groupby('color').transform(np.sum).add_prefix('tot_')


tot_price1  tot_price2
0        5.56        4.75
1        4.76        4.87
2        4.05        4.75
3        4.76        4.87
4        4.05        4.75

In [116]:
frame.groupby(['color']).apply( lambda x: x.max())

color  price1  price2
color                       
green  green    2.75    3.15
red      red    4.20    4.12
white  white    5.56    4.75